### ISSUE TITLE
Cannot read properties of undefined (reding 'pushManager')

### ISSUE THREAD

**Issue by NicoCaldo** [safwanrahman/django-webpush#134]
On Chrome I'm getting an error on line 95 of webpush.js when I try to subscribe with the error

```
Cannot read properties of undefined (reding 'pushManager')
at subscribe (webpush.js:95:7)
at HTMLButtonElement.<anonymous> (webpush.js:16:14)
```

I've correctly created the VAPID key like the documentation describe

**Comment by NicoCaldo** [comment]
Everything works fine in localhost but when I try to access my server within the local network using `http://my_ip` I got the error

**Comment by NicoCaldo** [comment]
It turned out you need your server to run on HTTPS

I have geenrated a self signed certificate on my server matching its IP and loclahost but now the error is 

```
An unknown error occurred when fetching the script.
my_ip/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://1my_ip:8080/webpush/') with script ('https://my_ip:8080/webpush/service-worker.js'): An unknown error occurred when fetching the script.
```

**Comment by NicoCaldo** [comment]
It seems the worker is not loaded in Chrome

**Comment by NicoCaldo** [comment]
Could it be chrome doesn't allow self-signed certificate for web workers?
