### ISSUE TITLE
Not sure if I am missing something with regard to the application server key?

### ISSUE THREAD

**Issue by marcuslavender** [safwanrahman/django-webpush#85]
Hi,

I have followed the instructions and can get my browser to subscribe for push notifications. But only if I manually edit the JS code.
It seems the code tries to generate the application server key from the Public key? Which in my case does not work. Not sure if this is how  it is supposed to work?
If I manually generate an application server key using pyvapid and enter this instead of the variable for line 109 it then subscribes successfully.
Am I missing something?

Here is the error I get:

webpush.js:141 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at urlB64ToUint8Array (https://blahblahblah.com:8000/static/webpush/webpush.js:141:26)
    at https://blahblahblah.com:8000/static/webpush/webpush.js:109:40

thanks

**Comment by marcuslavender** [comment]
Ok, Ignore this, it took me some time to realise the application server key should be entered and set to the public key param in Django.
